/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "New": "新",
    "All": "全部",
    "Potions": "药水",
    "Weapon Card": "武器卡",
    "To Recycle": "回收",
    "Conf": "配置",
    "Craft Card Upgrade": "工艺卡升级",
    "Crft": "工艺",
    "Crds": "卡牌",
    "Help": "帮助",
    "Map": "地图",
    "Rcyl": "回收",
    "Stat": "统计",
    "Send": "发送",
    "Bld": "建筑",
    "Acc": "账号",
    "Basic Range": "基础远程",
    "Basic Spell": "基础法术",
    "Next Level:": "下一级:",
    "Poison Arrow": "毒箭",
    "Range Skill": "远程技能",
    "Speed Shot": "快速射击",
    "Spell Skill": "法术技能",
    "Accurate": "命中",
    "All Unequipped Cards": "所有未装备的卡片",
    "Asbestos Lining": "石棉衬里",
    "Balanced": "平衡",
    "Basket Hilt": "篮柄",
    "Bloodbath": "血洗",
    "Bloodfingers": "血手指",
    "Brain Juice": "脑汁",
    "Breadhat": "面包帽",
    "Chest Card": "胸部卡牌",
    "Click an item above to equip cards": "单击上方的物品以装备卡片",
    "Compression Shorts": "压缩短裤",
    "Equipped Gear": "装备的装备",
    "Equipped Skills": "装备的技能",
    "gityx.com": "gityx.com",
    "Hands Card": "手部卡牌",
    "Head Card": "头部卡牌",
    "Head Of Vigor": "活力之首",
    "Heart Juice": "心脏果汁",
    "Hot Sword": "炽热之剑",
    "Legs Card": "腿部卡片",
    "Life On Hit": "击中生命",
    "New!": "新！",
    "Next Level Craftable!": "可升级！",
    "Nimble": "灵活",
    "Pinpoint Precision": "精确定位",
    "Pyromania": "纵火狂",
    "Skill Card": "技能卡牌",
    "Balsa Helmet": "轻木头盔",
    "Basic Melee": "基础近战",
    "Build Tab": "建筑选项卡",
    "Cardboard Sword": "纸板剑",
    "Chest Armor": "胸甲",
    "Cost is empty": "费用为空",
    "Dexterous Hands": "灵巧的手",
    "Dodgers Cap": "道奇队帽",
    "Empty": "空",
    "Energy": "能量",
    "Equipped Skill Cards": "装备技能卡牌",
    "Fire Ball": "火球",
    "Fire Slash": "火焰斩",
    "Goodness gracious, these balls are great!": "天哪，这些球很棒！",
    "Hands Armor": "手甲",
    "Head Armor": "头甲",
    "Jeans": "牛仔裤",
    "Latex Gloves": "乳胶手套",
    "Leather Boots": "皮靴",
    "Legs Armor": "腿甲",
    "Lethal Strike": "致命一击",
    "Mage Boots": "法师靴",
    "Mana On Hit": "击中法力",
    "Melee Skill": "近战技能",
    "Melee Weapon": "近战武器",
    "Metal": "金属",
    "Precise": "精准",
    "Range Weapon": "射程武器",
    "Razors": "剃须刀",
    "Rename Build": "重命名建筑",
    "Select a card to upgrade": "选择要升级的卡",
    "Sharpened": "锐化",
    "Six Pack": "六包",
    "Stinging": "刺痛",
    "T-shirt": "T恤",
    "Unequipped Skill Cards": "未装备技能卡牌",
    "Upgrading Precise": "升级精准",
    "Velvet Tunic": "天鹅绒束腰外衣",
    "Wooden Bow": "木弓",
    "Auto-advance on zone clear": "区域清除时自动前进",
    "Blood": "血液",
    "Brains": "大脑",
    "Feathers": "羽毛",
    "Select an item": "选择一个物品",
    "Spikes": "尖刺",
    "Hints:": "提示：",
    "-Click \"Card\" to equip cards": "-点击“卡牌”装备卡片",
    "-Click \"Craft\" to level up cards": "-点击“工艺”升级卡片",
    "-Click \"Inv\" to Change equipment and skills": "-点击“仓库”更改装备和技能",
    "-Click the Config button to change your name": "- 单击配置按钮更改您的名称",
    "-Click your potion to regain some health": "-点击你的药水恢复一些生命值",
    "Chat": "聊天",
    "Ebon Mourn - Art Assets": "Ebon Mourn - 艺术资产",
    "for more help": "寻求更多帮助",
    "Leaderboard": "排行榜",
    "Monster Compendium": "怪物纲要",
    "Please check out our": "请查看我们的",
    "Special Thanks": "特别感谢",
    "Subreddit": "Subreddit",
    "Text Tutorial": "文字教程",
    "Welcome to Dungeons of Derp": "欢迎来到放置地下城",
    "Accuracy": "精准",
    "AOE Radius": "AOE 半径",
    "AOE Speed": "AOE 速度",
    "Armor": "盔甲",
    "Avg % Chance to Hit": "平均 % 命中率",
    "Avg % Cold Taken": "平均 % 受到的冰霜伤害",
    "Avg % Dodge Chance (this zone)": "平均 % 闪避几率（此区域）",
    "Avg % Fire Taken": "平均 % 受到的火焰伤害",
    "Avg % Lightning Taken": "平均 % 受到的闪电伤害",
    "Avg % Physical Taken": "平均 % 受到的物理伤害",
    "Avg % Poison Taken": "平均 % 受到的中毒伤害",
    "Bat": "蝙蝠",
    "Blades": "刀片",
    "Bloodsucker": "吸血鬼",
    "Body": "身体",
    "Business Cards": "商业名片",
    "Character Version": "角色版本",
    "Clawed": "爪子",
    "Cold Damage": "寒冷伤害",
    "Cold Resistance": "冰霜抗性",
    "Cold Thorns": "冷刺",
    "Converters": "转换器",
    "Cool In": "冷却",
    "Cooldown Length": "冷却时间",
    "Crag Shards": "峭壁碎片",
    "Dexterity": "灵巧",
    "Dodge": "躲闪",
    "Elemental Resistance": "元素抗性",
    "Elf": "精灵",
    "Elf Ears": "精灵耳朵",
    "Embers": "余烬",
    "Equipped Chest Cards": "装备胸卡",
    "Equipped Hand Cards": "装备手部卡牌",
    "Eyes": "眼睛",
    "Fingers": "手指",
    "Fire Damage": "火灾伤害",
    "Fire Resistance": "火焰抗性",
    "Fire Thorns": "火荆棘",
    "Gargoyles": "石像鬼",
    "Gnomes": "侏儒",
    "Handles": "把手",
    "Health Gained on Hit": "击中获得的生命值",
    "Health Regenerated per Second": "每秒恢复生命值",
    "Hearts": "红心",
    "Ice": "冰",
    "Imp Heads": "小鬼头",
    "Last Death": "最后的死亡",
    "Leather Gloves": "皮手套",
    "Leeched Health": "生命值吸取",
    "Leeched Mana": "吸取的法力",
    "Level": "等级",
    "Lichen": "地衣",
    "Lightning Damage": "闪电伤害",
    "Lightning Resistance": "闪电抗性",
    "Lightning Thorns": "闪电荆棘",
    "Mana Cost": "法力消耗",
    "Mana Gained on Hit": "击中获得法力值",
    "Mana Regenerated per Second": "每秒法力回复",
    "Materials": "材料",
    "Max % Cold Taken": "最大冷量百分比",
    "Max % Fire Taken": "最大火力百分比",
    "Max % Lightning Taken": "最大百分比闪电",
    "Max % Physical Taken": "采取的最大体力百分比",
    "Max % Poison Taken": "最大毒药百分比",
    "Maximum Health": "最大生命值",
    "Maximum Mana": "最大法力",
    "Melee Damage": "近战伤害",
    "Min % Dodge Chance (this zone)": "最小 % 闪避几率（此区域）",
    "Mirrors": "镜子",
    "Movement Speed": "移动速度",
    "Muscles": "肌肉",
    "Name": "姓名",
    "Needles": "针",
    "Nightmares": "噩梦",
    "Physical Damage": "物理伤害",
    "Physical Thorns": "物理荆棘",
    "Poison Damage": "毒伤害",
    "Poison Resistance": "毒素抗性",
    "Poison Thorns": "毒刺",
    "Projectile Radius": "弹丸半径",
    "Projectile Range": "射程",
    "Projectile Speed": "弹丸速度",
    "Quick Hit": "快速命中",
    "Ranged Damage": "远程伤害",
    "Recycle everything and get nothing.": "回收一切，一无所获。",
    "Score": "分数",
    "Shields": "盾牌",
    "Sigils": "印记",
    "Simple Wand": "简单的魔杖",
    "Skill Duration": "技能持续时间",
    "Skill Range": "技能远程",
    "Skulls": "头骨",
    "Slime": "史莱姆",
    "Small Stature": "身材矮小",
    "Sparks": "火花",
    "Spec": "规格",
    "Spell Damage": "法术伤害",
    "Spell Weapon": "法术武器",
    "Spines": "刺",
    "Spores": "孢子",
    "Steady Hands": "稳定的手",
    "Strength": "力量",
    "Toes": "脚趾",
    "Unequipped Chest Cards": "未装备的胸部卡牌",
    "Unequipped Hand Cards": "未装备手部卡牌",
    "Vitality": "活力",
    "Wight Snow": "怀特雪",
    "Wings": "翅膀",
    "Wisdom": "智力",
    "Wood Nymph": "木若虫",
    "Hobbit Foot": "霍比特脚",
    "Scout Leather": "童军皮革",
    "Simple Minded": "简单的头脑",
    "Strong Back": "强壮的背部",
    "Thwomping": "怦怦直跳",
    "All donations will be rolled forward into our in-game paid currency system once implemented (donate $10, get $10 of in-game currency later based on email address used to donate)": "一旦实施，所有捐款都将转入我们的游戏内付费货币系统（捐赠 10 美元，稍后根据用于捐赠的电子邮件地址获得 10 美元的游戏内货币）",
    "Arcane Boots": "奥术长靴",
    "Automatically level up equipped cards": "自动升级装备的卡片",
    "Back": "后退",
    "Batsuit": "蝙蝠装",
    "Berserking": "狂暴",
    "Big": "好大",
    "Chinchilla Lining": "龙猫衬里",
    "Cold Blooded": "冷血",
    "Cold Sword": "寒剑",
    "Delicate Wand": "精致的魔杖",
    "Disable the shaking time bank's high speed shake effect": "禁用摇动时间银行的高速摇动效果",
    "Donate (via Stripe)": "捐赠（通过条纹）",
    "Donate to development of our game!": "为我们的游戏开发捐款！",
    "Elf Bow": "精灵弓",
    "Elf King": "精灵王",
    "Enable Save/Load builds with 0-9": "使用 0-9 启用保存/加载构建",
    "Ent": "耳鼻喉科",
    "Enter an amount in USD (min $1)": "输入美元金额（最低 1 美元）",
    "Equipped Head Cards": "装备头卡",
    "Equipped Leg Cards": "装备腿卡",
    "Equipped Weapon Cards": "装备武器卡",
    "Ethereal": "空灵",
    "Faster Attacks": "更快的攻击",
    "Fire Arrow": "火箭",
    "Fleece Lining": "羊毛衬里",
    "Frost Mage": "冰霜法师",
    "Frost Ritual": "冰霜仪式",
    "Frost Skeleton": "冰霜骷髅",
    "Frosted": "磨砂",
    "Frozen Warrior": "冰冻战士",
    "Fur Hat": "皮帽",
    "Gladiator Helm": "角斗士头盔",
    "Goblin Priest": "哥布林牧师",
    "Good Circulation": "良好的循环",
    "Handmail": "手信",
    "Happy Feet": "快乐的大脚",
    "Heart Of Granite": "花岗岩之心",
    "Hot Blooded": "热血的",
    "Ice Ball": "冰球",
    "Ice Blast": "冰爆",
    "Ice Golem": "冰魔像",
    "Ice Nova": "冰新星",
    "Ice Plating": "冰电镀",
    "Ice Slash": "冰斩",
    "Ice Spikes": "冰钉",
    "Ice-water in his veins...": "他的血管里有冰水……",
    "Iced": "冰镇",
    "Icy Hands": "冰霜之手",
    "Iron Chestplate": "铁胸甲",
    "Keen Wit": "机智",
    "Long Sword": "长剑",
    "Mage Hat": "法师帽",
    "Mageheart": "法师之心",
    "Magma in his veins...": "岩浆在他的血管里...",
    "Message to the devs?": "给开发者的信息？",
    "Mind Expansion": "思维扩展",
    "Movement Angle": "运动角度",
    "Note that at 10x speed you are 50% more inefficient and at 50x speed you are 100% more inefficient.": "请注意，在 10 倍的速度下，您的效率会降低 50%，而在 50 倍的速度下，您的效率会降低 100%。",
    "Pause on Boss": "遇见Boos时暂停",
    "Pause on Death": "死亡暂停",
    "Planet Buster": "星球破坏者",
    "Pyropotency": "焦潜能",
    "Quenching Blade": "淬火刀片",
    "Shadow Walker": "影行者",
    "Show Hero Damage Taken": "显示英雄受到的伤害",
    "Show Material Drops": "显示材料滴",
    "Show Monster Damage Taken": "显示怪物受到的伤害",
    "Super Smash": "超级粉碎",
    "Sure Footing": "稳扎稳打",
    "Unequipped Head Cards": "未装备的头部卡牌",
    "Unequipped Leg Cards": "未装备的腿部卡牌",
    "Unequipped Weapon Cards": "未装备的武器卡牌",
    "What is your name?": "你叫什么名字？",
    "When enabled, press Shift+0-9 to save build, 0-9 to load build": "启用后，按 Shift+0-9 保存构建，按 0-9 加载构建",
    "Wight": "怀特",
    "Wipe your game data and reset?  (no prestige bonuses - coming soon)": "擦除您的游戏数据并重置？ （没有声望奖金 - 即将推出）",
    "Yeti": "雪人",
    "Yeti Fur": "雪人皮草",
    "Zone on Death": "死亡地带",
    "Antibiotics": "抗生素",
    "Clown Shoes": "小丑鞋",
    "Hazmat Boots": "危险品靴子",
    "Hazmat Mask": "防毒面具",
    "Increased Radius": "增加半径",
    "Indigenous Toxins": "土著毒素",
    "Knee Pads": "护膝",
    "Minimum Tolerances": "最小公差",
    "More Projectiles": "更多弹丸",
    "Overdraw": "透支",
    "Plague Ritual": "瘟疫仪式",
    "Poison Ball": "毒球",
    "Poison Nova": "剧毒新星",
    "Poison Slash": "毒斩",
    "Potion Holster": "药水皮套",
    "Prismatic Toe Ring": "棱柱形脚趾环",
    "Reduced Radius": "缩小半径",
    "Shambling": "蹒跚",
    "Side Arm": "侧臂",
    "Swamp Armor": "沼泽护甲",
    "Unwashed Hands": "没洗过的手",
    "Accounts - In Construction - Use with Caution!": "帐户 - 建设中 - 谨慎使用！",
    "Careful! Prestiging early can lose progress": "小心！ 过早的声望可能会失去进步",
    "Create Account": "创建账户",
    "Hold Shift to spend max points": "按住 Shift 以花费最高点数",
    "Prestige": "声望",
    "Sign In": "登入",
    "Skeleton": "骨骼",
    "Skill Cannot Be Used Because Wrong Weapon Type Equipped": "由于装备了错误的武器类型，无法使用技能",
    "some newbie": "一些菜鸟",
    "Incinerate": "焚化",
    "Telescoping Handle": "伸缩手柄",
    "Alabaster": "雪花石膏",
    "Armor Plating": "装甲电镀",
    "Blast Arrow": "爆破箭",
    "Blazing": "炽烈",
    "Blazing Inferno": "炽热地狱",
    "Buckaneer Boots": "海盗靴子",
    "Conquistador Helm": "征服者头盔",
    "Cool Shoes": "酷鞋",
    "Creates small AoE explosions on hit": "击中时产生小型 AoE 爆炸",
    "Crossbow": "弩",
    "Fire Golem": "火傀儡",
    "Fire Skeleton": "火骷髅",
    "Firewalker": "火行者",
    "Flaming Debris": "燃烧的碎片",
    "Forest Spirit": "森林精神",
    "Gardening Gloves": "园艺手套",
    "Goblin": "地精",
    "Goblin Leather": "地精皮革",
    "Goblin Toe": "地精脚趾",
    "Ground Smash": "地面粉碎",
    "Ignited": "点燃",
    "Incinerate": "焚化",
    "More Physical Damage": "更多物理伤害",
    "Sopping Underclothes": "浸泡内衣",
    "Spikey Mace": "尖刺狼牙棒",
    "Telescoping Handle": "伸缩手柄",
    "The Inhuman Torch": "不人道的火炬",
    "Walter Wight": "沃尔特·怀特",
    "Buff": "增益",
    "Electropotency": "电势",
    "Flying": "飞行",
    "Harpy": "哈比",
    "Marshwalker": "沼泽行者",
    "Putrefied": "腐烂的",
    "Roflcopter": "直升机",
    "Static Socks": "静电袜",
    "Vest Pockets": "背心口袋",
    "all hail gaben": "万岁加本",
    "Blood Pact": "血之契约",
    "Chain Lightning": "闪电链",
    "Charged": "带电",
    "Charged Hands": "充电之手",
    "Clockwork": "发条",
    "Conductive Suit": "导电服",
    "Creates chained electical AoE explosions on kill": "击杀时产生连锁的电子 AoE 爆炸",
    "Eagle Eye": "鹰眼",
    "Electricians Gloves": "电工手套",
    "Electrified": "带电",
    "Enchant Weapon": "附魔武器",
    "Faster Propogation": "更快的传播",
    "Fire Nova": "火焰新星",
    "Flame Ritual": "火焰仪式",
    "Fortunately the path of least resistance is no longer through your heart.": "幸运的是，阻力最小的道路不再穿过你的心。",
    "Leatherscale Armor": "皮鳞甲",
    "Less Skill Duration means More Moving": "更少的技能持续时间意味着更多的移动",
    "Lightning Ball": "闪电球",
    "Lightning Slash": "闪电斩",
    "Mecha Heart": "机甲之心",
    "Mobility": "流动性",
    "Nanotube Reinforcement": "纳米管增强",
    "Nova": "新星",
    "Possessed Weapon": "拥有武器",
    "Pressure Wave": "压力波",
    "Refridgerator": "冰箱",
    "Riveted": "铆接",
    "Roller Skates": "溜冰鞋",
    "Rubber Boots": "橡胶靴",
    "Shock Ritual": "休克仪式",
    "Steam Powered": "蒸汽动力的",
    "Stone Hammer": "石锤",
    "Thunderstorm": "雷雨",
    "Tinfoil Hat": "锡箔帽",
    "Winged Axe": "飞斧",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Inv": "仓库",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "R": "R",
    "M": "M",
    "Sp": "法",
    "Sk": "技",
    "Ml": "战",
    "Ra": "远",
    "Lg": "腿",
    "He": "头",
    "Eq": "穿",
    "Ha": "手",
    "We": "武",
    "Ch": "胸",
    "Ueq": "脱",
    "Ent": "Ent",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Zone Name: ": "区域名称：",
    "spooky dungeon": "诡异地牢 ",
    "Current ": "当前 ",
    "Total Damage: ": "总计伤害：",
    "dark forest": "黑暗森林 ",
    "Cooldown: ": "冷却: ",
    "Duration: ": "持续时间: ",
    "Mana Cost: ": "法力成本: ",
    "Range: ": "远程: ",
    "DPS: ": "每秒伤害: ",
    "Next (": "下一个 (",
    "Level: ": "等级: ",
    "Upgrading ": "升级 ",
    "Version:": "版本：",
    "aggro crag": "仇恨之岩",
    "icy tunnel": "寒冰隧道",
    "hostile marsh": "敌意沼泽",
    "clockwork ruins": "发条废墟",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^XP ([\d\.]+) \/ ([\d\.]+)$/,
    /^XP ([\d\.]+) \/ ([\d\.]+)k$/,
    /^XP ([\d\.]+)k \/ ([\d\.]+)k$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)k$/,
    /^([\d\.]+)k\/([\d\.]+)k$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^↑([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\)$/,
    /^([\d\.,]+) ms$/,
    /^([\d\.,]+)k ms$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) remaining points$/, '你有 $1 剩余点数'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Recycle everything and get (.+) Handles.$/, '回收所有东西并获得 $1 个把手。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Last prestige was for (.+) prestige points.$/, '上次声望是在 $1 声望点。'],
    [/^Prestige now for (.+) prestige points.$/, '现在声望可获得 $1 声望点。'],
    [/^(.+) of Lightning Damage Converted To Cold Damage$/, '$1 的 闪电伤害 转换为 冰霜伤害'],
    [/^(.+) of Physical Damage Converted To Cold Damage$/, '$1 的 物理伤害 转换为 冰霜伤害'],
    [/^(.+) of Physical Damage Converted To Fire Damage$/, '$1 的 物理伤害 转换为 火焰伤害'],
    [/^(.+) of Physical Damage Converted To Lightning Damage$/, '$1 的 物理伤害 转换为 闪电伤害'],
    [/^(.+) of Maximum Health Gained As Health Regenerated per Second$/, '每秒恢复生命值时获得最大生命值的 $1'],
    [/^(.+) of Lightning Damage Gained As Leeched Health$/, '获得 闪电伤害 的 $1 作为生命吸取'],
    [/^(.+) of Cooldown Length Gained As Leeched Health$/, '获得 冷却时长 的 $1 作为生命吸取'],
    [/^(.+) of Physical Damage Gained As Leeched Health$/, '获得 物理伤害 的 $1 作为生命吸取'],
    [/^(.+) of Fire Damage Gained As Leeched Health$/, '获得 火焰伤害 的 $1 作为生命吸取'],
    [/^(.+) of Poison Damage Gained As Leeched Health$/, '获得 中毒伤害 的 $1 作为生命吸取'],
    [/^(.+) of Cold Damage Gained As Leeched Health$/, '获得 冰霜伤害 的 $1 作为生命吸取'],
    [/^(.+) of Wisdom Gained As Maximum Mana$/, '获得 智力 的 $1 作为法力上限'],
    [/^(.+) of Wisdom Gained As Leeched Health$/, '获得 智力 的 $1 作为生命吸取'],
    [/^(.+) of Physical Damage Converted To Poison Damage$/, '$1 物理伤害转换为毒伤害'],
    [/^\-(.+) Health Regenerated per Second$/, '$1 每秒恢复的生命值'],
    [/^(.+) Projectile Range$/, '$1 射程'],
    [/^(.+) Cooldown Length$/, '$1 冷却时长'],
    [/^(.+) More Projectile Range$/, '$1 更多的 射程'],
    [/^(.+) More Skill Range$/, '$1 更多的 技能范围'],
    [/^(.+) More Projectile Speed$/, '$1 更多的 射弹速度'],
    [/^(.+) More Movement Speed$/, '$1 更多的 移动速度'],
    [/^(.+) More Skill Duration$/, '$1 更多的 技能时长'],
    [/^(.+) More Character Height$/, '$1 更多的 角色高度'],
    [/^(.+) More Character Width$/, '$1 更多的 角色宽度'],
    [/^(.+) More AOE Radius$/, '$1 更多的 AOE 半径'],
    [/^(.+) More AOE Speed$/, '$1 更快的 AOE 速度'],
    [/^(.+) More Angle$/, '$1 更多的 角度'],
    [/^(.+) More Vitality$/, '$1 更多的 活力'],
    [/^(.+) More Strength$/, '$1 更多的 力量'],
    [/^(.+) More Dodge$/, '$1 更多的 闪避'],
    [/^(.+) More Dexterity$/, '$1 更多的 灵巧'],
    [/^(.+) More Wisdom$/, '$1 更多的 智力'],
    [/^(.+) More Armor$/, '$1 更多的 护甲'],
    [/^(.+) More Accuracy$/, '$1 更多的 精准'],
    [/^(.+) More Mana Cost$/, '$1 更多的 法力成本'],
    [/^(.+) More Mana Regenerated per Second$/, '$1 更多的 法力回复每秒'],
    [/^(.+) More Maximum Health$/, '$1 更多的 生命值上限'],
    [/^(.+) More Elemental Resistance$/, '$1 更多的 元素抗性'],
    [/^(.+) More Cold Damage$/, '$1 更多的 冰霜伤害'],
    [/^(.+) More Lightning Damage$/, '$1 更多的 闪电伤害'],
    [/^(.+) More Melee Damage$/, '$1 更多的 近战伤害'],
    [/^(.+) More Ranged Damage$/, '$1 更多的 远程伤害'],
    [/^(.+) More Poison Damage$/, '$1 更多的 中毒伤害'],
    [/^(.+) More Fire Damage$/, '$1 更多的 火焰伤害'],
    [/^(.+) More Lightning Resistance$/, '$1 更多的 闪电抗性'],
    [/^(.+) More Poison Resistance$/, '$1 更多的 中毒抗性'],
    [/^(.+) More Cold Resistance$/, '$1 更多的 冰霜抗性'],
    [/^(.+) More Fire Resistance$/, '$1 更多的 火焰抗性'],
    [/^(.+) More Spell Damage$/, '$1 更多的 法术伤害'],
    [/^(.+) More Physical Damage$/, '$1 更多的 物理伤害'],
    [/^(.+) More Projectile Radius$/, '$1 更多的 射弹半径'],
    [/^(.+) Less Character Height$/, '$1 更少的 角色高度'],
    [/^(.+) Less Projectile Speed$/, '$1 更少的 弹射速度'],
    [/^(.+) Less Armor$/, '$1 更少的 护甲'],
    [/^(.+) Less Wisdom$/, '$1 更少的 智力'],
    [/^(.+) Less Opacity$/, '$1 更少的 不透明度'],
    [/^(.+) Less Skill Duration$/, '$1 更少的 技能持续时长'],
    [/^(.+) Less Character Width$/, '$1 更少的 角色宽度'],
    [/^(.+) Less Cold Resistance$/, '$1 更少的 冰霜抗性'],
    [/^(.+) Less Lightning Resistance$/, '$1 更少的 闪电抗性'],
    [/^(.+) Less Fire Resistance$/, '$1 更少的 火焰抗性'],
    [/^(.+) Less Maximum Health$/, '$1 更少的 生命值上限'],
    [/^(.+) Less Movement Speed$/, '$1 更少的 移动速度'],
    [/^(.+) Less Fire Damage$/, '$1 更少的 火焰伤害'],
    [/^(.+) Less Lightning Damage$/, '$1 更少的 闪电伤害'],
    [/^(.+) Less Cold Damage$/, '$1 更少的 冰霜伤害'],
    [/^(.+) Less Ranged Damage$/, '$1 更少的 远程伤害'],
    [/^(.+) Less Spell Damage$/, '$1 更少的 法术伤害'],
    [/^(.+) Less Physical Damage$/, '$1 更少的 物理伤害'],
    [/^(.+) Less AOE Radius$/, '$1 更少的 AOE 半径'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Build ([\d\.,]+)$/, '建筑 $1'],
    [/^Lightning Resistance : (.+) \(costs (.+)\)$/, '闪电抗性 : $1 \(成本 $2\)'],
    [/^Poison Resistance : (.+) \(costs (.+)\)$/, '中毒抗性 : $1 \(成本 $2\)'],
    [/^Elemental Resistance : (.+) \(costs (.+)\)$/, '元素抗性 : $1 \(成本 $2\)'],
    [/^Cold Resistance : (.+) \(costs (.+)\)$/, '冰霜抗性 : $1 \(成本 $2\)'],
    [/^Fire Resistance : (.+) \(costs (.+)\)$/, '火焰抗性 : $1 \(成本 $2\)'],
    [/^Physical Damage : (.+) \(costs (.+)\)$/, '物理伤害 : $1 \(成本 $2\)'],
    [/^Ranged Damage : (.+) \(costs (.+)\)$/, '远程伤害 : $1 \(成本 $2\)'],
    [/^Cold Damage : (.+) \(costs (.+)\)$/, '冰霜伤害 : $1 \(成本 $2\)'],
    [/^Fire Damage : (.+) \(costs (.+)\)$/, '火焰伤害 : $1 \(成本 $2\)'],
    [/^Lightning Damage : (.+) \(costs (.+)\)$/, '闪电伤害 : $1 \(成本 $2\)'],
    [/^Poison Damage : (.+) \(costs (.+)\)$/, '中毒伤害 : $1 \(成本 $2\)'],
    [/^Spell Damage : (.+) \(costs (.+)\)$/, '法术伤害 : $1 \(成本 $2\)'],
    [/^Melee Damage : (.+) \(costs (.+)\)$/, '近战伤害 : $1 \(成本 $2\)'],
    [/^Maximum Mana : (.+) \(costs (.+)\)$/, '法力上限 : $1 \(成本 $2\)'],
    [/^Maximum Health : (.+) \(costs (.+)\)$/, '生命值上限 : $1 \(成本 $2\)'],
    [/^Dexterity : (.+) \(costs (.+)\)$/, '灵巧 : $1 \(成本 $2\)'],
    [/^Dodge : (.+) \(costs (.+)\)$/, '闪避 : $1 \(成本 $2\)'],
    [/^Wisdom : (.+) \(costs (.+)\)$/, '智力 : $1 \(成本 $2\)'],
    [/^Accuracy : (.+) \(costs (.+)\)$/, '精准 : $1 \(成本 $2\)'],
    [/^Armor : (.+) \(costs (.+)\)$/, '护甲 : $1 \(成本 $2\)'],
    [/^Vitality : (.+) \(costs (.+)\)$/, '活力 : $1 \(成本 $2\)'],
    [/^Strength : (.+) \(costs (.+)\)$/, '力量 : $1 \(成本 $2\)'],
    [/^\+(.+) Strength$/, '\+$1 力量'],
    [/^\+(.+) Dodge$/, '\+$1 闪避'],
    [/^\+(.+) Armor$/, '\+$1 护甲'],
    [/^\+(.+) Elemental Resistance$/, '\+$1 元素抗性'],
    [/^\+(.+) Line Width$/, '\+$1 线宽'],
    [/^\+(.+) Dexterity$/, '\+$1 灵巧'],
    [/^\+(.+) Wisdom$/, '\+$1 智力'],
    [/^\+(.+) Vitality$/, '\+$1 活力'],
    [/^\+(.+) Angle$/, '\+$1 角度'],
    [/^\+(.+) Additional Projectiles$/, '\+$1 额外的射弹'],
    [/^\+(.+) Health Regenerated per Second$/, '\+$1 生命值恢复每秒'],
    [/^\+(.+) Mana Gained on Hit$/, '\+$1 击中获得的法力值'],
    [/^\+(.+) Health Gained on Hit$/, '\+$1 击中获得的生命值'],
    [/^\+(.+) Mana Regenerated per Second$/, '\+$1 法力回复每秒'],
    [/^\+(.+) Cold Damage$/, '\+$1 冰霜伤害'],
    [/^\+(.+) Lightning Damage$/, '\+$1 闪电伤害'],
    [/^\+(.+) Physical Damage$/, '\+$1 物理伤害'],
    [/^\+(.+) Poison Damage$/, '\+$1 中毒伤害'],
    [/^\+(.+) Fire Damage$/, '\+$1 火焰伤害'],
    [/^\+(.+) Mana Cost$/, '\+$1 法力成本'],
    [/^\+(.+) Skill Duration$/, '\+$1 技能持续时间'],
    [/^\+(.+) Skill Range$/, '\+$1 技能远程'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);