/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "New": "新",
    "All": "全部",
    "Potions": "药水",
    "Weapon Card": "武器卡",
    "To Recycle": "回收",
    "Conf": "配置",
    "Craft Card Upgrade": "工艺卡升级",
    "Crft": "工艺",
    "Crds": "卡牌",
    "Help": "帮助",
    "Map": "地图",
    "Rcyl": "回收",
    "Stat": "属性",
    "Send": "发送",
    "Bld": "建筑",
    "Acc": "账号",
    "Basic Range": "基础范围",
    "Basic Spell": "基础法术",
    "Next Level:": "下一级:",
    "Poison Arrow": "毒箭",
    "Range Skill": "范围技能",
    "Speed Shot": "快速射击",
    "Spell Skill": "法术技能",
    "Accurate": "命中",
    "All Unequipped Cards": "所有未装备的卡片",
    "Asbestos Lining": "石棉衬里",
    "Balanced": "平衡",
    "Basket Hilt": "篮柄",
    "Bloodbath": "血洗",
    "Bloodfingers": "血手指",
    "Brain Juice": "脑汁",
    "Breadhat": "面包帽",
    "Chest Card": "胸卡",
    "Click an item above to equip cards": "单击上方的物品以装备卡片",
    "Compression Shorts": "压缩短裤",
    "Equipped Gear": "装备的装备",
    "Equipped Skills": "装备的技能",
    "gityx.com": "gityx.com",
    "Hands Card": "手部卡牌",
    "Head Card": "头部卡牌",
    "Head Of Vigor": "活力之首",
    "Heart Juice": "心脏果汁",
    "Hot Sword": "炽热之剑",
    "Legs Card": "腿部卡片",
    "Life On Hit": "击中生命",
    "New!": "新！",
    "Next Level Craftable!": "下一级可制作！",
    "Nimble": "灵活",
    "Pinpoint Precision": "精确定位",
    "Pyromania": "纵火狂",
    "Skill Card": "技能卡",
    "Balsa Helmet": "轻木头盔",
    "Basic Melee": "基础近战",
    "Build Tab": "建筑选项卡",
    "Cardboard Sword": "纸板剑",
    "Chest Armor": "胸甲",
    "Cost is empty": "费用为空",
    "Dexterous Hands": "灵巧的手",
    "Dodgers Cap": "道奇队帽",
    "Empty": "空",
    "Energy": "能量",
    "Equipped Skill Cards": "装备技能卡",
    "Fire Ball": "火球",
    "Fire Slash": "火焰斩",
    "Goodness gracious, these balls are great!": "天哪，这些球很棒！",
    "Hands Armor": "手甲",
    "Head Armor": "头甲",
    "Jeans": "牛仔裤",
    "Latex Gloves": "乳胶手套",
    "Leather Boots": "皮靴",
    "Legs Armor": "腿甲",
    "Lethal Strike": "致命一击",
    "Mage Boots": "法师靴",
    "Mana On Hit": "击中法力",
    "Melee Skill": "近战技能",
    "Melee Weapon": "近战武器",
    "Metal": "金属",
    "Precise": "精确的",
    "Range Weapon": "射程武器",
    "Razors": "剃须刀",
    "Rename Build": "重命名构建",
    "Select a card to upgrade": "选择要升级的卡",
    "Sharpened": "锐化",
    "Six Pack": "六包",
    "Stinging": "刺痛",
    "T-shirt": "T恤",
    "Unequipped Skill Cards": "未装备技能卡",
    "Upgrading Precise": "升级精准",
    "Velvet Tunic": "天鹅绒束腰外衣",
    "Wooden Bow": "木弓",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Inv": "仓库",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "R": "R",
    "M": "M",
    "Sp": "Sp",
    "Sk": "Sk",
    "Ml": "Ml",
    "Ra": "Ra",
    "Lg": "Lg",
    "He": "He",
    "Eq": "Eq",
    "Ha": "Ha",
    "We": "We",
    "Ch": "Ch",
    "Ueq": "Ueq",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "spooky dungeon ": "诡异地牢 ",
    "Current ": "当前 ",
    "Total Damage: ": "总计伤害：",
    "dark forest ": "黑暗森林 ",
    "Cooldown: ": "冷却: ",
    "Duration: ": "持续时间: ",
    "Mana Cost: ": "法力成本: ",
    "Range: ": "范围: ",
    "DPS: ": "每秒伤害: ",
    "Next (": "下一个 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)\%$/,
    /^XP ([\d\.]+) \/ ([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)k$/,
    /^([\d\.]+)k\/([\d\.]+)k$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) ms$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) Cooldown Length$/, '$1 冷却长度'],
    [/^(.+) More Movement Speed$/, '$1 更多的 移动速度'],
    [/^(.+) More Skill Duration$/, '$1 更多的 技能时长'],
    [/^(.+) More Dexterity$/, '$1 更多的 灵巧'],
    [/^(.+) More Armor$/, '$1 更多的 护甲'],
    [/^(.+) More Accuracy$/, '$1 更多的 活力'],
    [/^(.+) More Mana Regenerated per Second$/, '$1 更多的 法力回复每秒'],
    [/^(.+) More Maximum Health$/, '$1 更多的 生命值上限'],
    [/^(.+) More Elemental Resistance$/, '$1 更多的 元素抗性'],
    [/^(.+) More Ranged Damage$/, '$1 更多的 范围伤害'],
    [/^(.+) More Poison Damage$/, '$1 更多的 中毒伤害'],
    [/^(.+) More Fire Damage$/, '$1 更多的 火焰伤害'],
    [/^(.+) More Fire Resistance$/, '$1 更多的 火焰抗性'],
    [/^(.+) More Spell Damage$/, '$1 更多的 法术伤害'],
    [/^(.+) More Physical Damage$/, '$1 更多的 物理伤害'],
    [/^(.+) More Projectile Radius$/, '$1 更多的 抛射体半径'],
    [/^(.+) Less Fire Resistance$/, '$1 更少的 火焰抗性'],
    [/^(.+) Less Physical Damage$/, '$1 更少的 物理伤害'],
    [/^(.+) Less AOE Radius$/, '$1 更少的 AOE 半径'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Build ([\d\.,]+)$/, '建筑 $1'],
    [/^\+(.+) Dodge$/, '\+$1 闪避'],
    [/^\+(.+) Armor$/, '\+$1 护甲'],
    [/^\+(.+) Elemental Resistance$/, '\+$1 元素抗性'],
    [/^\+(.+) Line Width$/, '\+$1 线宽'],
    [/^\+(.+) Dexterity$/, '\+$1 灵巧'],
    [/^\+(.+) Vitality$/, '\+$1 活力'],
    [/^\+(.+) Health Regenerated per Second$/, '\+$1 生命值恢复每秒'],
    [/^\+(.+) Mana Gained on Hit$/, '\+$1 击中获得的法力值'],
    [/^\+(.+) Health Gained on Hit$/, '\+$1 击中获得的生命值'],
    [/^\+(.+) Mana Regenerated per Second$/, '\+$1 法力回复每秒'],
    [/^\+(.+) Physical Damage$/, '\+$1 物理伤害'],
    [/^\+(.+) Fire Damage$/, '\+$1 火焰伤害'],
    [/^\+(.+) Mana Cost$/, '\+$1 法力成本'],
    [/^\+(.+) Skill Duration$/, '\+$1 技能持续时间'],
    [/^\+(.+) Skill Range$/, '\+$1 技能范围'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);